name: 'medicore'
version: '1.0.0'
config-version: 2

profile: 'medicore'

model-paths: ["models"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

on-run-end: "{{ log_run_summary(results) }}"

vars:
  run_id: 'manual'

models:
  medicore:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: MARTS
    audit:
      +materialized: view
      +schema: AUDIT
