medicore:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE_NAME') }}"
      database: MEDICORE_DEV
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_NAME') }}"
      schema: STAGING
      threads: 4

    test:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE_NAME') }}"
      database: MEDICORE_TEST
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_NAME') }}"
      schema: STAGING
      threads: 4

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE_NAME') }}"
      database: MEDICORE
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_NAME') }}"
      schema: STAGING
      threads: 8
