-- 0. Utiliser un rôle admin
USE ROLE ACCOUNTADMIN;

-- 1. Utiliser le warehouse par défaut COMPUTE_WH (existant)
USE WAREHOUSE COMPUTE_WH;  

-- 2. Créer le Warehouse (taille SMALL pour tests, scale à MEDIUM/LARGE en prod)
CREATE OR REPLACE WAREHOUSE MEDICORE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60		-- arrêt automatique du warehouse après 60 s d'inactivité (valeur optimisée)
    AUTO_RESUME = TRUE		-- Quand une nouvelle requête arrive sur un warehouse suspendu, il redémarre 	instantanément (< 2s de délai).
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse MEDICORE ELT pipeline';

-- 3. Créer la Database et Schema RAW
CREATE OR REPLACE DATABASE MEDICORE
    COMMENT = 'Database MEDICORE - Pharmacie analytics';

-- 4. Créer les schemas
USE DATABASE MEDICORE;

-- CREATE OR REPLACE SCHEMA MEDICORE.RAW
CREATE OR REPLACE SCHEMA RAW
    COMMENT = 'RAW layer - Données brutes MySQL CDC vers Kafka';

-- CREATE OR REPLACE SCHEMA MEDICORE.STAGING
CREATE OR REPLACE SCHEMA STAGING
    COMMENT = 'STAGING layer - Données nettoyées/dédupliquées';

-- CREATE OR REPLACE SCHEMA MEDICORE.MARTS
CREATE OR REPLACE SCHEMA MARTS
    COMMENT = 'MART layer - Dimensions et faits analytiques';

CREATE OR REPLACE SCHEMA AUDIT
    COMMENT = 'AUDIT layer - Suivi des runs dbt et métriques qualité';

-- 5. Créer rôles dédiés (RBAC)
CREATE OR REPLACE ROLE MEDICORE_RAW_WRITER
    COMMENT = 'Rôle pour RAW CDC writer';

CREATE OR REPLACE ROLE MEDICORE_DBT_EXECUTOR
    COMMENT = 'Rôle pour dbt executor : read RAW, write STAGING/MARTS';

CREATE OR REPLACE ROLE MEDICORE_ANALYST
    COMMENT = 'Rôle pour Analyst read-only';

-- 6. Grants Warehouse usage aux rôles
ALTER WAREHOUSE MEDICORE_WH RESUME;     -- MEDICORE_WH est créé en état SUSPENDU  (INITIALLY_SUSPENDED = TRUE)
USE WAREHOUSE MEDICORE_WH;

GRANT USAGE, MONITOR ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_RAW_WRITER;     
GRANT USAGE, MONITOR ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_DBT_EXECUTOR;   
GRANT USAGE ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_ANALYST;

-- 7. Grants DB
GRANT USAGE ON DATABASE MEDICORE TO ROLE MEDICORE_RAW_WRITER;
GRANT USAGE, CREATE SCHEMA ON DATABASE MEDICORE TO ROLE MEDICORE_DBT_EXECUTOR;  -- dbt exécute CREATE SCHEMA IF NOT EXISTS
GRANT USAGE ON DATABASE MEDICORE TO ROLE MEDICORE_ANALYST;

-- 8. Grants Schemas 
GRANT ALL PRIVILEGES ON SCHEMA RAW TO ROLE MEDICORE_RAW_WRITER;           -- dbt RAW
GRANT ALL PRIVILEGES ON SCHEMA STAGING TO ROLE MEDICORE_DBT_EXECUTOR;     -- dbt STAGING
GRANT ALL PRIVILEGES ON SCHEMA MARTS TO ROLE MEDICORE_DBT_EXECUTOR;       -- dbt MARTS
GRANT ALL PRIVILEGES ON SCHEMA AUDIT TO ROLE MEDICORE_DBT_EXECUTOR;       -- dbt AUDIT
GRANT USAGE ON SCHEMA RAW TO ROLE MEDICORE_DBT_EXECUTOR;                  -- dbt read RAW
GRANT USAGE ON SCHEMA MARTS TO ROLE MEDICORE_ANALYST;                     -- Analyst read
GRANT USAGE ON SCHEMA AUDIT TO ROLE MEDICORE_ANALYST;                     -- Analyst read AUDIT

-- 9. FUTURE TABLES & VIEWS (CRITIQUE pour incremental MERGE)
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FUTURE TABLES IN SCHEMA RAW TO ROLE MEDICORE_RAW_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FUTURE TABLES IN SCHEMA STAGING TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FUTURE TABLES IN SCHEMA MARTS TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE MEDICORE_ANALYST;                     -- Analyst lit AUDIT
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE MEDICORE_DBT_EXECUTOR;                 -- dbt lit RAW
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STAGING TO ROLE MEDICORE_DBT_EXECUTOR;              -- dbt crée des vues staging

-- 10. Grants sur tables EXISTANTES (FUTURE ne couvre pas les tables déjà créées)
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AUDIT TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT SELECT ON ALL TABLES IN SCHEMA AUDIT TO ROLE MEDICORE_ANALYST;

-- 11. Associer rôles à un utilisateur
GRANT ROLE MEDICORE_RAW_WRITER TO USER AUGUSTIN;
GRANT ROLE MEDICORE_DBT_EXECUTOR TO USER AUGUSTIN;

-- 12. Vérification
SELECT 'MEDICORE DDL SUCCESS - dbt READY' AS status;
SHOW GRANTS TO ROLE MEDICORE_RAW_WRITER;
SHOW GRANTS TO ROLE MEDICORE_DBT_EXECUTOR;