-- RAW_COMMANDES (PK: PHA_ID, COM_GROI, PRD_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_COMMANDES (
    PHA_ID NUMBER NOT NULL,
    COM_GROI NUMBER NOT NULL,
    PRD_ID NUMBER NOT NULL,
    COM_GROS NUMBER NOT NULL,
    COM_DATE DATE NOT NULL,
    FOU_ID VARCHAR(16),
    COM_QUANTITE NUMBER(5,0) NOT NULL,
    COM_PAHTNET NUMBER(8,2),
    COM_TAUXREMISE NUMBER(6,2),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, COM_GROI, PRD_ID)
);

-- RAW_DAYBYDAY (PK: PHA_ID, DBD_DATE, PRD_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_DAYBYDAY (
    PHA_ID NUMBER NOT NULL,
    DBD_DATE DATE NOT NULL,
    PRD_ID NUMBER NOT NULL,
    DBD_PRIXTARIF NUMBER(8,2) NOT NULL,
    DBD_PRIXPUBLIC NUMBER(8,2) NOT NULL,
    DBD_PAMP NUMBER(8,2) NOT NULL,
    DBD_PANET NUMBER(8,2),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, DBD_DATE, PRD_ID)
);

-- RAW_EAN13 (PK: PHA_ID, EAN_13, PRD_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_EAN13 (
    PHA_ID NUMBER NOT NULL,
    EAN_13 VARCHAR(16) NOT NULL,
    PRD_ID NUMBER NOT NULL,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, EAN_13, PRD_ID)
);

-- RAW_FACTURES (PK: PHA_ID, FAC_ID, FAC_TI)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_FACTURES (
    PHA_ID NUMBER NOT NULL,
    FAC_ID NUMBER NOT NULL,
    FAC_TI NUMBER NOT NULL,
    FAC_BASE NUMBER NOT NULL,
    FAC_DATE TIMESTAMP_NTZ NOT NULL,
    PRD_ID NUMBER NOT NULL,
    FAC_TVA NUMBER(6,2) NOT NULL,
    FAC_QUANTITE NUMBER(5,0) NOT NULL,
    FAC_PAHT NUMBER(8,2) NOT NULL,
    FAC_PVHT NUMBER(8,2) NOT NULL,
    FAC_PVTTC NUMBER(8,2) NOT NULL,
    FAC_PRIXPUBLIC NUMBER(8,2) NOT NULL,
    FAC_REMISE NUMBER(6,2) NOT NULL,
    FAC_CODEREMBT NUMBER(5,0) NOT NULL,
    FAC_HISTO_NBCLIENT NUMBER(5,0) NOT NULL,
    FAC_PROMO NUMBER NOT NULL,
    FAC_RETRO NUMBER NOT NULL,
    FAC_LOCATION NUMBER NOT NULL,
    FAC_ORDO NUMBER NOT NULL,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, FAC_ID, FAC_TI)
);

-- RAW_FOURNISSEURS (PK: PHA_ID, FOU_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_FOURNISSEURS (
    PHA_ID NUMBER NOT NULL,
    FOU_ID VARCHAR(16) NOT NULL,
    FOU_NOM VARCHAR(50),
    FOU_ADRESSE VARCHAR(50),
    FOU_CP VARCHAR(12),
    FOU_VILLE VARCHAR(50),
    FOU_TYPE NUMBER(5,0),
    FOU_REPARTITEUR NUMBER,
    FOU_ETABLISSEMENT VARCHAR(32),
    FOU_IDCLIENT VARCHAR(16),
    FOU_URL1 VARCHAR(255),
    FOU_URL2 VARCHAR(255),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, FOU_ID)
);

-- RAW_HISTORY (PK: PHA_ID, Date)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_HISTORY (
    PHA_ID NUMBER NOT NULL,
    "Date" DATE NOT NULL,  -- "Date" est un mot-clé, utiliser en quotes
    EspeceFRF NUMBER(10,2) NOT NULL,
    ChequeFRF NUMBER(10,2) NOT NULL,
    CB NUMBER(10,2) NOT NULL,
    Centre NUMBER(10,2) NOT NULL,
    Differe_Positif NUMBER(10,2) NOT NULL,
    nb_De_Factures NUMBER NOT NULL,
    nb_De_Subro NUMBER NOT NULL,
    TVA_1 NUMBER(10,2) NOT NULL,
    TVA_2 NUMBER(10,2) NOT NULL,
    TVA_3 NUMBER(10,2) NOT NULL,
    TVA_4 NUMBER(10,2) NOT NULL,
    TVA_5 NUMBER(10,2) NOT NULL,
    Marge_Rembt NUMBER(10,2) NOT NULL,
    Marge_NRembt NUMBER(10,2) NOT NULL,
    Remise_EnCompte NUMBER(10,2) NOT NULL,
    Remise_EnLigne NUMBER(10,2) NOT NULL,
    EnCompte_Positif NUMBER(10,2) NOT NULL,
    Mutuelle NUMBER(10,2) NOT NULL,
    EspeceEUR NUMBER(10,2) NOT NULL,
    ChequeEUR NUMBER(10,2) NOT NULL,
    Virement NUMBER(10,2) NOT NULL,
    SubroPartAssure NUMBER(10,2) NOT NULL,
    Controle NUMBER(10,2) NOT NULL,
    PointsFidel NUMBER(10,2) NOT NULL,
    Particulier NUMBER(10,2) NOT NULL,
    EnCompteBL_Positif NUMBER(10,2) NOT NULL,
    Differe_Negatif NUMBER(10,2) NOT NULL,
    EnCompte_Negatif NUMBER(10,2) NOT NULL,
    EnCompteBL_Negatif NUMBER(10,2) NOT NULL,
    CA_Retro_1 NUMBER(10,2) NOT NULL,
    CA_Retro_2 NUMBER(10,2) NOT NULL,
    CA_Retro_3 NUMBER(10,2) NOT NULL,
    CA_Retro_4 NUMBER(10,2) NOT NULL,
    CA_Retro_5 NUMBER(10,2) NOT NULL,
    DMPositif NUMBER(10,2) NOT NULL,
    DMNegatif NUMBER(10,2) NOT NULL,
    DMRetroPositif NUMBER(10,2) NOT NULL,
    DMRetroNegatif NUMBER(10,2) NOT NULL,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, "Date")
);

-- RAW_LOG (PK: PHA_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_LOG (
    PHA_ID NUMBER NOT NULL,
    DATE_SYNC TIMESTAMP_NTZ,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID)
);

-- RAW_LPPR (PK: PHA_ID, PRD_ID, LPP_INDEX, LPP_CODE)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_LPPR (
    PHA_ID NUMBER NOT NULL,
    PRD_ID NUMBER NOT NULL,
    LPP_INDEX NUMBER NOT NULL,
    LPP_CODE VARCHAR(14) NOT NULL,
    LPP_QTE NUMBER NOT NULL,
    LPP_ACTE_NOM VARCHAR(20) NOT NULL,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, PRD_ID, LPP_INDEX, LPP_CODE)
);

-- RAW_MANQHISTORY (PK: PHA_ID, MNQ_DATE, PRD_ID, FAC_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_MANQHISTORY (
    PHA_ID NUMBER NOT NULL,
    MNQ_DATE DATE NOT NULL,
    PRD_ID NUMBER NOT NULL,
    FAC_ID NUMBER NOT NULL,
    EN_LIGNES NUMBER NOT NULL,
    EN_BOITES NUMBER NOT NULL,
    EN_CLIENTS NUMBER NOT NULL,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, MNQ_DATE, PRD_ID, FAC_ID)
);

-- RAW_MEDIPRIX_FACTURES (PK: PHA_ID, FAC_ID, FAC_TI)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_MEDIPRIX_FACTURES (
    id NUMBER,
    PHA_ID NUMBER NOT NULL,
    FAC_ID NUMBER NOT NULL,
    FAC_TI NUMBER NOT NULL,
    FAC_DATE DATE,
    FAC_HEURE VARCHAR(25),
    FAC_TVA FLOAT,
    FAC_QUANTITE NUMBER,
    FAC_PAHT FLOAT,
    FAC_PVHT FLOAT,
    FAC_PVTTC FLOAT,
    FAC_PRIXPUBLIC FLOAT,
    FAC_CODEREMBT NUMBER,
    PRD_ID NUMBER,
    PRD_EAN13 VARCHAR(13),
    PRD_NOM VARCHAR(150),
    ORD_OPERATEUR VARCHAR(25),
    PHA_NOM VARCHAR(50),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, FAC_ID, FAC_TI)
);

-- RAW_MODSTOCK (PK: PHA_ID, MOD_DATE, PRD_ID, MOD_TIMESTAMP)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_MODSTOCK (
    PHA_ID NUMBER NOT NULL,
    MOD_DATE TIMESTAMP_NTZ NOT NULL,
    PRD_ID NUMBER NOT NULL,
    MOD_TIMESTAMP NUMBER NOT NULL,
    MOD_DELTA NUMBER(5,0) NOT NULL,
    MOD_TI NUMBER NOT NULL,
    MOD_STOCK NUMBER(5,0) NOT NULL,
    MOD_FACTURE NUMBER,
    MOD_COMMANDE NUMBER,
    MOD_OPERATION NUMBER,
    MOD_PARAM2 NUMBER,
    MOD_POSTE VARCHAR(16),
    MOD_DELTA_RESERVE NUMBER(5,0),
    MOD_CODE_ZONE NUMBER(5,0),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, MOD_DATE, PRD_ID, MOD_TIMESTAMP)
);

-- RAW_ORDERS (PK: PHA_ID, FAC_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_ORDERS (
    PHA_ID NUMBER NOT NULL,
    FAC_ID NUMBER NOT NULL,
    ORD_DATE TIMESTAMP_NTZ NOT NULL,
    ORD_OPERATEUR VARCHAR(40) NOT NULL,
    ORD_CLIENT_AGE_MONTHS NUMBER(5,0),
    ORD_CLIENT_SEX VARCHAR(1),
    ORD_CLIENT_DEPARTMENT VARCHAR(2),
    ORD_HISTO_NBCLIENT NUMBER(5,0) NOT NULL,
    ORD_BASE NUMBER NOT NULL,
    ORD_RETRO NUMBER NOT NULL,
    ORD_LOCATION NUMBER NOT NULL,
    ORD_ORDO NUMBER NOT NULL,
    ORD_AVR NUMBER NOT NULL,
    ORD_ANN NUMBER NOT NULL,
    ORD_DATE_ORDON TIMESTAMP_NTZ,
    ORD_DATE_ORDER TIMESTAMP_NTZ,
    ORD_CODE_SUBRO VARCHAR(4),
    ORD_TOTAL_GENERAL NUMBER(8,2),
    ORD_TOTAL_REMB_SS NUMBER(8,2),
    ORD_TOTAL_REMB_MUTU NUMBER(8,2),
    ORD_CLI_TI NUMBER,
    ORD_BEN_TI NUMBER(5,0),
    ORD_MED_TI NUMBER,
    ORD_MED_SPEC NUMBER(5,0),
    ORD_OPER_CODE NUMBER(5,0),
    ORD_CLI_TYPE NUMBER(3,0),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, FAC_ID)
);

-- RAW_PHARMACIE (PK: PHA_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_PHARMACIE (
    PHA_ID NUMBER NOT NULL,
    PHA_IDNAT VARCHAR(10) NOT NULL,
    PHA_GERS VARCHAR(7),
    PHA_NOM VARCHAR(100) NOT NULL,
    PHA_DATE_INSTAL_WP DATE,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID)
);

-- RAW_PRODUITS (PK: PHA_ID, PRD_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_PRODUITS (
    PHA_ID NUMBER NOT NULL,
    PRD_ID NUMBER NOT NULL,
    PRD_EAN13 VARCHAR(16),
    PRD_NOM VARCHAR(50),
    PRD_IDMAJPRD NUMBER,
    FOU_ID VARCHAR(16),
    PRD_CODEREMBT NUMBER(5,0),
    PRD_CODEACTE VARCHAR(4),
    PRD_FIRSTSTOCK TIMESTAMP_NTZ,
    PRD_TVA NUMBER(6,2),
    PRD_NTVA NUMBER(5,0),
    PRD_CREATE DATE,
    PRD_STOCK NUMBER(5,0),
    PRD_PRIXTARIF NUMBER(8,2),
    PRD_DERN_VENTE DATE,
    PRD_DERN_ACHAT DATE,
    PRD_FLAG3 NUMBER(5,0),
    PRD_REFGEN NUMBER(5,0),
    PRD_EN_STOCK NUMBER,
    PRD_EN_COMMANDE NUMBER,
    PRD_EN_PROMIS NUMBER,
    PRD_DELETED NUMBER,
    PRD_ONLYPROMIS NUMBER,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, PRD_ID)
);

-- RAW_PRODUITS_NEGATIFS (PK: PRD_ID)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_PRODUITS_NEGATIFS (
    PRD_ID NUMBER NOT NULL,
    PRD_NOM VARCHAR(150),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PRD_ID)
);

-- RAW_STOCKHISTORY (PK: PHA_ID, PRD_ID, STH_DATE)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_STOCKHISTORY (
    PHA_ID NUMBER NOT NULL,
    PRD_ID NUMBER NOT NULL,
    STH_DATE DATE NOT NULL,
    STH_STOCKDELTA NUMBER(5,0) NOT NULL,
    STH_STOCK NUMBER(5,0),
    STH_PRIXTARIF NUMBER(8,2),
    STH_PRIXPUBLIC NUMBER(8,2),
    STH_PAMP NUMBER(8,2),
    STH_PANET NUMBER(8,2),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (PHA_ID, PRD_ID, STH_DATE)
);

-- RAW_PHARMACIES (PK: id)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_pharmacies (
    id NUMBER NOT NULL,
    adeli VARCHAR(50),
    name VARCHAR(50),
    phone VARCHAR(50),
    city VARCHAR(50),
    postal_code VARCHAR(50),
    parent_id NUMBER,
    left_groupment BOOLEAN NOT NULL DEFAULT FALSE,
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (id)
);

-- RAW_PHARMACIES_ERREUR (PK: id)
CREATE OR REPLACE TABLE MEDICORE.RAW.RAW_pharmacies_erreur (
    id NUMBER,
    code_erreur NUMBER,
    date_erreur TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    cdc_operation VARCHAR(1),
    cdc_timestamp TIMESTAMP_NTZ,
    cdc_lsn VARCHAR(255),
    PRIMARY KEY (id)
);
