-- 0. Utiliser un rôle admin
USE ROLE ACCOUNTADMIN;

-- 1. Utiliser le warehouse par défaut ACCOUNTADMIN (existant)
USE WAREHOUSE COMPUTE_WH;  

-- 2. Créer le Warehouse (taille SMALL pour tests, scale à MEDIUM/LARGE en prod)
CREATE OR REPLACE WAREHOUSE MEDICORE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60		-- arrêt automatique du warehouse après 60 s d'inactivité (valeur optimisée)
    AUTO_RESUME = TRUE		-- Quand une nouvelle requête arrive sur un warehouse suspendu, il redémarre 	instantanément (< 2s de délai).
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse dédié MEDICORE ELT pipeline';

-- 3. Créer la Database et Schema RAW
CREATE OR REPLACE DATABASE MEDICORE
    COMMENT = 'Database MEDICORE - Pharmacie analytics';

-- 4. Créer les schemas
USE DATABASE MEDICORE;

-- CREATE OR REPLACE SCHEMA MEDICORE.RAW
CREATE OR REPLACE SCHEMA RAW
    COMMENT = 'RAW layer - Données brutes depuis MySQL CDC';

-- CREATE OR REPLACE SCHEMA MEDICORE.STAGING
CREATE OR REPLACE SCHEMA STAGING
    COMMENT = 'STAGING layer - Données nettoyées/dédupliquées';

-- CREATE OR REPLACE SCHEMA MEDICORE.MARTS
CREATE OR REPLACE SCHEMA MARTS
    COMMENT = 'MART layer - Dimensions et faits analytiques';

-- 5. Créer rôles dédiés (RBAC)
CREATE OR REPLACE ROLE MEDICORE_RAW_WRITER
    COMMENT = 'Rôle pour écrire en RAW depuis Python/CDC loader';

CREATE OR REPLACE ROLE MEDICORE_DBT_EXECUTOR
    COMMENT = 'Rôle pour dbt : read RAW, write STAGING/MARTS';

CREATE OR REPLACE ROLE MEDICORE_ANALYST
    COMMENT = 'Rôle lecture MARTS pour analystes';

-- 6. Grants Warehouse usage aux rôles
ALTER WAREHOUSE MEDICORE_WH RESUME;     -- MEDICORE_WH est créé en état SUSPENDU  (INITIALLY_SUSPENDED = TRUE)
USE WAREHOUSE MEDICORE_WH;

GRANT USAGE ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_RAW_WRITER;
GRANT USAGE ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT USAGE ON WAREHOUSE MEDICORE_WH TO ROLE MEDICORE_ANALYST;

-- 7. Grants DB (CREATE SCHEMA implicite)
GRANT USAGE ON DATABASE MEDICORE TO ROLE MEDICORE_RAW_WRITER;
GRANT USAGE ON DATABASE MEDICORE TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT USAGE ON DATABASE MEDICORE TO ROLE MEDICORE_ANALYST;

-- 8. Grants Schemas 
GRANT CREATE TABLE, USAGE ON SCHEMA RAW TO ROLE MEDICORE_RAW_WRITER;
GRANT USAGE ON SCHEMA RAW TO ROLE MEDICORE_DBT_EXECUTOR;

GRANT CREATE TABLE, USAGE ON SCHEMA STAGING TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT USAGE ON SCHEMA STAGING TO ROLE MEDICORE_ANALYST;

GRANT CREATE TABLE, USAGE ON SCHEMA MARTS TO ROLE MEDICORE_DBT_EXECUTOR;
GRANT USAGE ON SCHEMA MARTS TO ROLE MEDICORE_ANALYST;

-- 9. Associer rôles à un utilisateur
GRANT ROLE MEDICORE_RAW_WRITER TO USER AUGUSTIN;
GRANT ROLE MEDICORE_DBT_EXECUTOR TO USER AUGUSTIN;

-- 10. Vérification
SELECT 'SUCCESS' AS status;